spring.datasource.url=jdbc:postgresql://localhost:5432/motion_industries
spring.datasource.username=${USER}
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
